//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kmuss.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class emploe
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> naprovlenierabot { get; set; }
        public int IDnaprovlenie { get; set; }
    }
}
