//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kmuss.model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class kmusEntities2 : DbContext
    {
        public kmusEntities2()
            : base("name=kmusEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admin { get; set; }
        public virtual DbSet<emploe> emploe { get; set; }
        public virtual DbSet<kc1> kc1 { get; set; }
        public virtual DbSet<naprovlenie> naprovlenie { get; set; }
        public virtual DbSet<oplatarabota> oplatarabota { get; set; }
        public virtual DbSet<platamaterial> platamaterial { get; set; }
        public virtual DbSet<rabota> rabota { get; set; }
        public virtual DbSet<reg> reg { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<vr1> vr1 { get; set; }
    }
}
