//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kmuss.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class naprovlenie
    {
        public int IDnaprovlenie { get; set; }
        public string naprovlenierabot1 { get; set; }
    }
}
