//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kmuss.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class platamaterial
    {
        public int ID { get; set; }
        public string name { get; set; }
        public Nullable<int> ed { get; set; }
        public Nullable<int> kol_vo { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<int> theamount { get; set; }
        public Nullable<int> intotal { get; set; }
    }
}
