//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kmuss.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vr1
    {
        public string naprovlenierabot { get; set; }
        public string vidwork { get; set; }
        public string ed { get; set; }
        public string kol_vo { get; set; }
    }
}
